apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-forgejo
spec:
  instances: 3

  superuserSecret:
    name: cnpg-forgejo-superuser

  bootstrap:
    initdb:
      database: forgejo
      owner: forgejo
      secret:
        name: cnpg-forgejo-app-user
  storage:
    size: 10Gi
