# https://code.forgejo.org/forgejo-helm/forgejo-helm/src/branch/main/values.yaml

#clusterDomain: irminsul

service:
  http:
    type: LoadBalancer
    annotations:
      kube-vip.io/loadbalancerIPs: 192.168.13.6
  ssh:
    type: LoadBalancer
    annotations:
      kube-vip.io/loadbalancerIPs: 192.168.13.6

persistence:
  storageClass: cephfs

# a large part of this just gets patched out (all the config in secrets, so hot right now)
# but just for reference in case we want to deactivate the delete patches for debugging
gitea:
  admin:
    existingSecret: forgejo-admin-secret
    email: forgejo@irminsul
  config:
    APP_NAME: "The Ebon Enginarium: Dark Dreams Deprave Decrepit Dungeon Dwelling Developer."
    server:
      DOMAIN: forgejo.irminsul
    # we can pass passwords for valkey in the connection string e.g.:
    # redis://password123@valkey:6379/0?
    queue:
      TYPE: redis
      CONN_STR: redis://valkey:6379/0?
    cache:
      ADAPTER: redis
      HOST: redis://valkey:6379/1
    session:
      PROVIDER: redis
      PROVIDER_CONFIG: redis://valeky:6379/2
  ui:
    DEFAULT_THEME: forgejo-dark
    # CUSTOM_EMOJIS: todo
